# 🧠 Data Preprocessing Practice Problem

## 📌 Objective
You are given a dataset related to employee information. Your task is to perform **complete data preprocessing**, including:

1. Importing necessary libraries
2. Loading the dataset
3. Handling missing values
4. Encoding categorical variables
5. Splitting the dataset into training and testing sets
6. Applying feature scaling

---

## 📊 Dataset Description

The dataset contains information about employees and whether they purchased a product.

### Columns:
- `Age` → Age of the employee (numerical)
- `Gender` → Male/Female (categorical)
- `Salary` → Annual salary (numerical)
- `Department` → Department name (categorical)
- `Experience` → Years of experience (numerical)
- `Purchased` → Target variable (0 = No, 1 = Yes)

---

## ⚙️ Tasks

### 1. Import Libraries
- Import NumPy, Pandas, Matplotlib (optional), and Scikit-learn

### 2. Load Dataset
- Read the CSV file into a Pandas DataFrame

### 3. Handle Missing Data
- Identify missing values
- Replace missing numerical values with **mean**
- Replace missing categorical values with **most frequent value**

### 4. Encode Categorical Data
- Apply **Label Encoding** for binary categorical variables (e.g., Gender)
- Apply **One-Hot Encoding** for multi-class categorical variables (e.g., Department)

### 5. Split Dataset
- Separate features (X) and target (y)
- Split into **Training Set (80%)** and **Test Set (20%)**

### 6. Feature Scaling
- Apply **Standardization (StandardScaler)** to numerical features

---

## 📁 Dataset (CSV Format)

Save the following as `employee_data.csv`:


# Solution :

## Importing Libraries

In [14]:
import pandas as pd
import numpy as np

## Loading dataset

In [15]:
df = pd.read_csv('./data.csv')
df = df[['Age', 'Gender', 'Department', 'Salary', 'Experience', 'Purchased']]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Age         50 non-null     int64  
 1   Gender      46 non-null     str    
 2   Department  47 non-null     str    
 3   Salary      47 non-null     float64
 4   Experience  50 non-null     int64  
 5   Purchased   50 non-null     str    
dtypes: float64(1), int64(2), str(3)
memory usage: 2.5 KB


## Separating feature matrix and dependant vector

In [16]:
X = np.array(df.iloc[:, :-1])
y = np.array(df.iloc[:, -1])

## Filling missing values

In [17]:
from sklearn.impute import SimpleImputer

mode_strategy = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

mode_strategy.fit(X[:, 1:3])
X[:, 1:3] = mode_strategy.transform(X[:, 1:3])

avg_strategy = SimpleImputer(missing_values=np.nan, strategy='mean')

avg_strategy.fit(X[:, 3:4])
X[:, 3:4] = avg_strategy.transform(X[:, 3:4])

print(X)

[[25 'Female' 'Marketing' 87127.65957446808 2]
 [34 'Female' 'Engineering' 78000.0 8]
 [41 'Female' 'Sales' 95000.0 15]
 [29 'Non-binary' 'HR' 61000.0 4]
 [52 'Male' 'Engineering' 115000.0 22]
 [22 'Female' 'Marketing' 87127.65957446808 1]
 [38 'Male' 'Finance' 82000.0 11]
 [45 'Female' 'Sales' 105000.0 18]
 [31 'Male' 'HR' 67000.0 6]
 [27 'Female' 'Engineering' 58000.0 3]
 [48 'Male' 'Finance' 120000.0 20]
 [33 'Female' 'Marketing' 72000.0 7]
 [26 'Male' 'Sales' 54000.0 2]
 [55 'Female' 'Engineering' 135000.0 28]
 [40 'Non-binary' 'Finance' 89000.0 13]
 [23 'Male' 'HR' 48000.0 1]
 [36 'Female' 'Marketing' 81000.0 9]
 [30 'Male' 'Sales' 69000.0 5]
 [44 'Female' 'Engineering' 102000.0 16]
 [50 'Female' 'HR' 118000.0 24]
 [28 'Female' 'Finance' 56000.0 4]
 [32 'Male' 'Marketing' 74000.0 6]
 [42 'Female' 'Sales' 98000.0 14]
 [35 'Male' 'Engineering' 80000.0 10]
 [53 'Female' 'Finance' 128000.0 25]
 [24 'Non-binary' 'Marketing' 50000.0 2]
 [39 'Male' 'HR' 87000.0 12]
 [46 'Female' 'Sales' 

## Encoding categorical data

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 25 87127.65957446808 2]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 34 78000.0 8]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 41 95000.0 15]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 29 61000.0 4]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 52 115000.0 22]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 22 87127.65957446808 1]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 38 82000.0 11]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 45 105000.0 18]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 31 67000.0 6]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 27 58000.0 3]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 48 120000.0 20]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 33 72000.0 7]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 26 54000.0 2]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 55 135000.0 28]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 40 89000.0 13]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 23 48000.0 1]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 36 81000.0 9]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 30 69000.0 5]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 44 102000.0 16]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 50 118000.0 24]
 [1.0

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 1 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0
 1 1 0 0 1 1 0 1 0 1 0 0 1]


## Splitting Data into test set and training set

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train[:, 8:11] = sc.fit_transform(X_train[:, 8:11])

X_test[:, 8:11] = sc.transform(X_test[:, 8:11])

In [22]:
print(X_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.1964490962174616 -1.367553915859317
  -1.241501361221542]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.4680199831533314 1.0747652524022215
  1.2921748861693598]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 -0.3766124564110637
  -0.36660343706360454 -0.35471467463472633]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 -0.6840511963384629 -0.8470596668855466
  -0.7347661117433616]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 -0.8890103562900623 -1.0872877817965176
  -0.9881337364824517]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.033305863492135206
  -0.24648937960811904 -0.10134704989563616]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.033305863492135206
  -0.12637532215263353 0.025336762473908925]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.3407446034195344 0.1939288310619945
  0.27870438721299906]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 -0.27413287643526396
  -0.20645136045629053 -0.22803086226518124]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 -1.5038878361448607 -1.6077820307702881
  -1.368185173591087]
 [1.0 0.0 0.0 1.0 0.0 0.0 0

In [23]:
print(X_test)

[[1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.7754587230807306 1.8755256354387917
  2.0522777603866302]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 -0.7865307763142626 -0.726945609430061
  -0.7347661117433616]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 -0.06917371648366452
  -0.16641334130446203 -0.10134704989563616]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 -0.47909203638686343
  -0.5267555136709186 -0.4813984870042714]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 -0.7865307763142626 -0.7669836285818896
  -0.8614499241129067]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 -1.401408256169061 -0.04118804736150919
  -1.241501361221542]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.13578544346793492
  -0.046299283848976525 0.025336762473908925]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 -1.401408256169061 -1.5277059924666312
  -1.241501361221542]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.1964490962174616 -1.3275158967074887
  -1.1148175488519967]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.263060823201732 1.194879309857707
  1.54554251090845]]


In [24]:
print(y_train)

[0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1
 0 0 1]


In [25]:
print(y_test)

[1 0 0 0 0 0 1 0 0 1]


## Saving training and test data into separate files

In [26]:
train_data = np.column_stack((X_train, y_train))
df_train = pd.DataFrame(train_data)
df_train.to_csv('Processed_Training_Data.csv', index=False)

test_data = np.column_stack((X_test, y_test))
df_test = pd.DataFrame(test_data)
df_test.to_csv('Processed_Test_Data.csv', index=False)