## 1. Creating 1D arrays (Vectors)

In [5]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(type(a))

print("\nProperties :-\n")
print("Shape = " +str(a.shape))
print("No of Dimensions = " +str(a.ndim))
print("Size = " +str(a.size))
print("Data type = " +str(a.dtype))

[1 2 3 4]
<class 'numpy.ndarray'>

Properties :-

Shape = (4,)
No of Dimensions = 1
Size = 4
Data type = int64


## 2. Creating 2D Arrays (Matrices)

In [8]:
b = np.array([[1,2,3],[4,5,6]])

print(b)
print(type(b))

print("\nProperties :-\n")
print("Shape = " +str(b.shape))
print("No of Dimensions = " +str(b.ndim))
print("Size = " +str(b.size))
print("Data type = " +str(b.dtype))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

Properties :-

Shape = (2, 3)
No of Dimensions = 2
Size = 6
Data type = int64


### Special Arrays

In [ ]:
np.zeros((3,3)) # Creates a 2D matrix where every element is 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,3)) # Creates a 2D matrix where every element is 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(4) # Creates an identity matrix of size N

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#np.arange(start, stop, step)
np.arange(0, 20, 2) # Creates a 1D array containing all elements from the start(inclusive) till the end(not inclusive) based on the amount of step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [58]:
#np.linspace(start, stop, num)
np.linspace(0, 1, 5) # Creates a 1D array containing 'num' number of evenly spaced numbers between start and stop (both inclusive)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Indexing and Slicing

In [66]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
print(a[0, 1]) # Access element at row 0 and column 1

2


In [68]:
print(a[1, :]) # Access the entire row 1

[4 5 6]


In [69]:
print(a[:, 2]) # Access the entire column 2

[3 6 9]


In [77]:
print(a[1:3, 0:2]) # Access the 2x2 submatrix from position (1,0) to (2,1)

[[4 5]
 [7 8]]


### Element-Wise operations

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x + y)
print(x - y)
print(x * y) # Not matrix multiplication
print(x / y)
print(x ** 2)
print(y ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[16 25 36]


## Matrix Multiplication

In [88]:
m = np.array([[1,2],[4,5]])
n = np.array([[-2,3], [-6,-10]])

print("m = ")
print(m)

print("\nn = ")
print(n)

print("\nm X n = ")
print(m @ n)

print("\nTranspose of m = ")
print(m.T)

m = 
[[1 2]
 [4 5]]

n = 
[[ -2   3]
 [ -6 -10]]

m X n = 
[[-14 -17]
 [-38 -38]]

Transpose of m = 
[[1 4]
 [2 5]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])

print("Matrix A = ")
print(a)

print("\nMean of matrix A :- ")
print(np.mean(a))

print("\nMean of all columns of matrix A :- ")
print(np.mean(a, axis=0)) # Collapses all rows i.e. adds all the rows together and finds average for each number

print("\nMean of all rows of matrix A :- ")
print(np.mean(a, axis=1)) # Collapses all columns i.e. add all the columns together and finds average for each number

Matrix A = 
[[1 2 3]
 [4 5 6]]

Mean of matrix A :- 
3.5

Mean of all columns of matrix A :- 
[2.5 3.5 4.5]

Mean of all rows of matrix A :- 
[2. 5.]


## Random Numbers

In [ ]:
np.random.rand(3,3) # Creates a matrix filled with random values from [0 to 1)

array([[0.11370707, 0.86922046, 0.07559176],
       [0.60947866, 0.79921683, 0.72092503],
       [0.33982273, 0.58377284, 0.1211125 ]])

In [291]:
np.random.randn(3,3) # Creates a matrix filled with random values from the normal distribution

array([[-6.61378173e-02, -3.78578670e-01, -7.41791607e-01],
       [ 6.07774009e-01, -7.20686424e-01,  1.07827905e+00],
       [ 4.65939987e-01, -9.79664967e-04, -5.23782360e-01]])

In [297]:
a = np.array([[1,2], [3,4]])
print("Matrix A :-")
print(a)

print("\nDeterminant of A :-")
print(np.linalg.det(a))
print("\nInverse of A :-")
print(np.linalg.inv(a))
print("\nEigenvalues and EigenVectors of A :-")
print(np.linalg.eig(a))

Matrix A :-
[[1 2]
 [3 4]]

Determinant of A :-
-2.0000000000000004

Inverse of A :-
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues and EigenVectors of A :-
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
