# Data Preprocessing Tools

## Importing the libraries required

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [45]:
df = pd.read_csv('./Data.csv')

In [46]:
# Features Matrix of the dataset
# Contains all the features of the dataset
X = df.iloc[:, :-1].values

# Dependant variable vector
y = df.iloc[:, -1].values

In [47]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 47.0 75000.0]
 ['France' 54.0 nan]
 ['France' 61.0 48000.0]
 ['France' 42.0 90000.0]
 ['France' 58.0 75000.0]
 ['France' nan 55000.0]]


In [48]:
print(y)

<StringArray>
[ 'No', 'Yes',  'No',  'No', 'Yes', 'Yes',  'No', 'Yes',  'No', 'Yes', 'Yes',
 'Yes',  'No',  'No', 'Yes']
Length: 15, dtype: str


## Taking care of missing data

In [49]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3]) # Looks for all missing values in the columns age and salary
X[:, 1:3] = imputer.transform(X[:, 1:3]) # Updates the missign values with the mean value of the column and assigns it

In [50]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 65384.61538461538]
 ['France' 35.0 58000.0]
 ['Spain' 44.15384615384615 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 47.0 75000.0]
 ['France' 54.0 65384.61538461538]
 ['France' 61.0 48000.0]
 ['France' 42.0 90000.0]
 ['France' 58.0 75000.0]
 ['France' 44.15384615384615 55000.0]]


## Encoding Categorical Data

### Encoding Independent Variable

In [51]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Transformers option requires 3 parameters :
# Type of transformation to be performed = 'encoder'
# Class which performs the above transformation = OneHotEncoder()
# Indexes of the columns to perform the transformations = 0

# remainder parameter 'passthrough' ensures that the other columns for which OneHotEncoding() is not applied will also be included. To not include them, we can exclude this parameter

# One Hot Encoding is used to encode multiple categories of given columns in a dataset
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [52]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 65384.61538461538]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 44.15384615384615 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 47.0 75000.0]
 [1.0 0.0 0.0 54.0 65384.61538461538]
 [1.0 0.0 0.0 61.0 48000.0]
 [1.0 0.0 0.0 42.0 90000.0]
 [1.0 0.0 0.0 58.0 75000.0]
 [1.0 0.0 0.0 44.15384615384615 55000.0]]


### Encoding dependant variable

In [53]:
from sklearn.preprocessing import LabelEncoder

# Label Encoding is used when we have only two cateories in a column
le = LabelEncoder()
y = le.fit_transform(y)

In [54]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 1 0 0 1]


## Splitting Data into Training Set and Test Set

In [55]:
from sklearn.model_selection import train_test_split

# test_train_split function splits the dataset into 4 parts :
# X_train = Contains the features matrix of the training set
# X_test = Contains the dependant variable vector of the training set
# y_train = Contains the features matrix of the test set
# y_test = Contains the dependant variable vector of the test set

# test_size parameter decides the percent of entries to be present in the test set i.e. 0.2 implies 20%
# random_state = 1, ensures that the split is not randomly changes every time the line executes
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [56]:
print(X_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 54.0 65384.61538461538]
 [0.0 1.0 0.0 40.0 65384.61538461538]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 58.0 75000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 44.15384615384615 55000.0]
 [1.0 0.0 0.0 47.0 75000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 42.0 90000.0]
 [1.0 0.0 0.0 61.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [57]:
print(X_test)

[[0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 44.15384615384615 52000.0]]


In [58]:
print(y_train)

[0 1 1 1 0 0 1 1 0 0 1 1]


In [59]:
print(y_test)

[0 1 0]


## Feature Scaling

In [60]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# The line below calculates the mean and standard deviation for the numeric columns and then transforms it in the training feature set
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# The line below uses the same scalar as the training set to just transform the test feature set. We should not fit a new scalar for the test set.
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [61]:
print(X_train)

[[0.0 1.0 0.0 -1.4259753145275946 -0.8997337220897718]
 [1.0 0.0 0.0 0.9595705199636092 -0.02654951966822315]
 [0.0 1.0 0.0 -0.43199788348959306 -0.02654951966822315]
 [0.0 0.0 1.0 -1.7241685438389953 -1.3599253963389664]
 [1.0 0.0 0.0 1.3571614923788098 0.7109371377824094]
 [1.0 0.0 0.0 -0.03440691107439242 0.48084130065781205]
 [1.0 0.0 0.0 -0.019114950596884756 -0.823035109714906]
 [1.0 0.0 0.0 0.2637863182370081 0.7109371377824094]
 [0.0 1.0 0.0 0.5619795475484086 1.3245260367813354]
 [1.0 0.0 0.0 -0.23320239728199274 1.861416323405396]
 [1.0 0.0 0.0 1.6553547216902105 -1.3599253963389664]
 [1.0 0.0 0.0 -0.9289865990085939 -0.5929392725903087]]


In [62]:
print(X_test)

[[0.0 0.0 1.0 -0.6307933696971934 -0.3628434354657114]
 [1.0 0.0 0.0 0.3631840613408082 1.0177315872818724]
 [0.0 0.0 1.0 -0.019114950596884756 -1.0531309468395034]]
